import React, { useState, useEffect, useCallback, useRef } from 'react';
import { useTranslation, Trans } from 'react-i18next';
import { X, Calendar, Users, Target, Plus, Trash2, AlertTriangle, Dices } from 'lucide-react';
import { MealPlanCreate, MealPlanEntryCreate, MealPlan } from '../../types';
import Button from '../ui/Button';
import Input from '../ui/Input';
import NumericInput from '../ui/NumericInput';
import Card, { CardContent, CardHeader, CardTitle } from '../ui/Card';
import RecipeSearchSelect from '../recipes/RecipeSearchSelect';
import useApi from '../../hooks/useApi';
import { createMealPlan, autoGenerateMealPlan, updateMealPlan, suggestMeal } from '../../api/mealPlanApi';
import { getLocaleFromLanguage } from '../../utils/i18nUtils';

const DRAFT_STORAGE_KEY = 'mealPlanDraft';
const DRAFT_AUTOGENERATE_STORAGE_KEY = 'mealPlanAutoGenerateDraft';

interface DraftData {
  formData: MealPlanCreate;
  autoGenerateData: {
    start_date: string;
    days: number;
    target_calories: number;
    people_count: number;
    dietary_preferences: string[];
    user_id: number;
  };
  isAutoGenerate: boolean;
  savedAt: number;
}

const getNextWeekMonday = (): string => {
  const today = new Date();
  const dayOfWeek = today.getDay();
  const daysUntilMonday = (8 - dayOfWeek) % 7 || 7;
  const nextMonday = new Date(today);
  nextMonday.setDate(today.getDate() + daysUntilMonday);
  return nextMonday.toISOString().split('T')[0];
};

const getSundayFromMonday = (mondayDate: string): string => {
  const monday = new Date(mondayDate);
  const sunday = new Date(monday);
  sunday.setDate(monday.getDate() + 6);
  return sunday.toISOString().split('T')[0];
};

interface CreateMealPlanModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess: () => void;
  editingMealPlan?: MealPlan | null;
}

const nextMonday = getNextWeekMonday();

const CreateMealPlanModal: React.FC<CreateMealPlanModalProps> = ({
  isOpen,
  onClose,
  onSuccess,
  editingMealPlan = null
}) => {
  const { t, i18n } = useTranslation();
  const isEditing = !!editingMealPlan;
  const [isAutoGenerate, setIsAutoGenerate] = useState(false);
  const [generatedMealPlan, setGeneratedMealPlan] = useState<MealPlan | null>(null);
  // Index of the meal entry currently being re-rolled (null = none in flight)
  const [rerollingIndex, setRerollingIndex] = useState<number | null>(null);
  const [formData, setFormData] = useState<MealPlanCreate>({
    start_date: nextMonday,
    end_date: getSundayFromMonday(nextMonday),
    people_count: 2,
    target_calories: 2000,
    dietary_preferences: [],
    entries: []
  });

  type AutoGenerateData = {
    start_date: string;
    days: number;
    target_calories: number;
    people_count: number;
    dietary_preferences: string[];
    user_id: number;
  };

  const [autoGenerateData, setAutoGenerateData] = useState<AutoGenerateData>({
    start_date: nextMonday,
    days: 7,
    target_calories: 2000,
    people_count: 2,
    dietary_preferences: [],
    user_id: 1
  });

  // Draft and dirty state management
  const [isDirty, setIsDirty] = useState(false);
  const [showDraftRestorePrompt, setShowDraftRestorePrompt] = useState(false);
  const [showCloseConfirm, setShowCloseConfirm] = useState(false);
  const [showRegenerateConfirm, setShowRegenerateConfirm] = useState(false);
  const [savedDraft, setSavedDraft] = useState<DraftData | null>(null);
  const draftSaveTimeoutRef = useRef<NodeJS.Timeout | null>(null);
  const hasInitializedRef = useRef(false);

  // Helper to get default form values
  const getDefaultFormData = useCallback((): MealPlanCreate => {
    const defaultStartDate = getNextWeekMonday();
    return {
      start_date: defaultStartDate,
      end_date: getSundayFromMonday(defaultStartDate),
      people_count: 2,
      target_calories: 2000,
      dietary_preferences: [],
      entries: []
    };
  }, []);

  const getDefaultAutoGenerateData = useCallback((): AutoGenerateData => {
    const defaultStartDate = getNextWeekMonday();
    return {
      start_date: defaultStartDate,
      days: 7,
      target_calories: 2000,
      people_count: 2,
      dietary_preferences: [],
      user_id: 1
    };
  }, []);

  // Save draft to localStorage with debounce
  const saveDraft = useCallback(() => {
    if (isEditing) return; // Don't save drafts when editing existing meal plans
    
    const draft: DraftData = {
      formData,
      autoGenerateData,
      isAutoGenerate,
      savedAt: Date.now()
    };
    localStorage.setItem(DRAFT_STORAGE_KEY, JSON.stringify(draft));
  }, [formData, autoGenerateData, isAutoGenerate, isEditing]);

  // Clear draft from localStorage
  const clearDraft = useCallback(() => {
    localStorage.removeItem(DRAFT_STORAGE_KEY);
    localStorage.removeItem(DRAFT_AUTOGENERATE_STORAGE_KEY);
    setIsDirty(false);
  }, []);

  // Load draft from localStorage
  const loadDraft = useCallback((): DraftData | null => {
    try {
      const draftJson = localStorage.getItem(DRAFT_STORAGE_KEY);
      if (draftJson) {
        const draft = JSON.parse(draftJson) as DraftData;
        // Check if draft is less than 24 hours old
        if (Date.now() - draft.savedAt < 24 * 60 * 60 * 1000) {
          return draft;
        } else {
          // Draft is too old, clear it
          clearDraft();
        }
      }
    } catch (e) {
      console.error('Failed to load draft:', e);
      clearDraft();
    }
    return null;
  }, [clearDraft]);

  // Restore draft data
  const restoreDraft = useCallback((draft: DraftData) => {
    setFormData(draft.formData);
    setAutoGenerateData(draft.autoGenerateData);
    setIsAutoGenerate(draft.isAutoGenerate);
    setShowDraftRestorePrompt(false);
    setSavedDraft(null);
    setIsDirty(true);
  }, []);

  // Decline draft restore
  const declineDraftRestore = useCallback(() => {
    clearDraft();
    setShowDraftRestorePrompt(false);
    setSavedDraft(null);
  }, [clearDraft]);

  // Check for saved draft when modal opens
  useEffect(() => {
    if (isOpen && !isEditing && !hasInitializedRef.current) {
      hasInitializedRef.current = true;
      const draft = loadDraft();
      if (draft) {
        setSavedDraft(draft);
        setShowDraftRestorePrompt(true);
      }
    }
    
    if (!isOpen) {
      hasInitializedRef.current = false;
    }
  }, [isOpen, isEditing, loadDraft]);

  // Debounced draft saving when form data changes
  useEffect(() => {
    if (!isOpen || isEditing || !isDirty) return;

    if (draftSaveTimeoutRef.current) {
      clearTimeout(draftSaveTimeoutRef.current);
    }

    draftSaveTimeoutRef.current = setTimeout(() => {
      saveDraft();
    }, 1000); // Save draft 1 second after last change

    return () => {
      if (draftSaveTimeoutRef.current) {
        clearTimeout(draftSaveTimeoutRef.current);
      }
    };
  }, [formData, autoGenerateData, isAutoGenerate, isOpen, isEditing, isDirty, saveDraft]);

  // beforeunload handler to warn on browser refresh/close
  useEffect(() => {
    const handleBeforeUnload = (e: BeforeUnloadEvent) => {
      if (isDirty && isOpen && !isEditing) {
        // Save draft immediately before unload
        saveDraft();
        e.preventDefault();
        e.returnValue = '';
        return '';
      }
    };

    window.addEventListener('beforeunload', handleBeforeUnload);
    return () => window.removeEventListener('beforeunload', handleBeforeUnload);
  }, [isDirty, isOpen, isEditing, saveDraft]);

  const { loading: creating, execute: createPlan } = useApi(createMealPlan);
  const { loading: updating, execute: updatePlan } = useApi(updateMealPlan);
  const { loading: autoGenerating, execute: autoGenerate } = useApi(autoGenerateMealPlan);

  // Initialize form data when editing meal plan changes
  useEffect(() => {
    if (editingMealPlan) {
      const startDate = editingMealPlan.start_date.split('T')[0];
      const endDate = editingMealPlan.end_date.split('T')[0];

      setFormData({
        start_date: startDate,
        end_date: endDate,
        people_count: editingMealPlan.people_count,
        target_calories: editingMealPlan.target_calories,
        dietary_preferences: [...editingMealPlan.dietary_preferences],
        entries: editingMealPlan.entries.map(entry => ({
          recipe_id: entry.recipe_id,
          date: entry.date.split('T')[0],
          meal_type: entry.meal_type,
          servings: entry.servings
        }))
      });

      // Disable auto-generate mode when editing
      setIsAutoGenerate(false);
    } else if (generatedMealPlan) {
      const startDate = generatedMealPlan.start_date.split('T')[0];
      const endDate = generatedMealPlan.end_date.split('T')[0];

      setFormData({
        start_date: startDate,
        end_date: endDate,
        people_count: generatedMealPlan.people_count,
        target_calories: generatedMealPlan.target_calories,
        dietary_preferences: [...generatedMealPlan.dietary_preferences],
        entries: generatedMealPlan.entries.map(entry => ({
          recipe_id: entry.recipe_id,
          date: entry.date.split('T')[0],
          meal_type: entry.meal_type,
          servings: entry.servings
        }))
      });

      setIsAutoGenerate(false);
    } else {
      const defaultStartDate = getNextWeekMonday();
      const defaultEndDate = getSundayFromMonday(defaultStartDate);
      setFormData({
        start_date: defaultStartDate,
        end_date: defaultEndDate,
        people_count: 2,
        target_calories: 2000,
        dietary_preferences: [],
        entries: []
      });
      setAutoGenerateData({
        start_date: defaultStartDate,
        days: 7,
        target_calories: 2000,
        people_count: 2,
        dietary_preferences: [],
        user_id: 1
      });
    }
  }, [editingMealPlan, generatedMealPlan]);

  const dietaryOptions = [
    { value: 'vegetarian', label: t('dietary.vegetarian') },
    { value: 'vegan', label: t('dietary.vegan') },
    { value: 'gluten-free', label: t('dietary.glutenFree') },
    { value: 'dairy-free', label: t('dietary.dairyFree') },
    { value: 'keto', label: t('dietary.keto') },
    { value: 'low-carb', label: t('dietary.lowCarb') },
    { value: 'high-protein', label: t('dietary.highProtein') },
  ];

  const handleInputChange = <K extends keyof MealPlanCreate>(field: K, value: MealPlanCreate[K]) => {
    setFormData(prev => ({ ...prev, [field]: value }));
    setIsDirty(true);
  };

  const handleAutoGenerateChange = <K extends keyof AutoGenerateData>(field: K, value: AutoGenerateData[K]) => {
    setAutoGenerateData(prev => ({ ...prev, [field]: value }));
    setIsDirty(true);
  };

  const toggleDietaryPreference = (preference: string) => {
    setIsDirty(true);
    if (isAutoGenerate) {
      setAutoGenerateData(prev => ({
        ...prev,
        dietary_preferences: prev.dietary_preferences.includes(preference)
          ? prev.dietary_preferences.filter(p => p !== preference)
          : [...prev.dietary_preferences, preference]
      }));
    } else {
      setFormData(prev => ({
        ...prev,
        dietary_preferences: prev.dietary_preferences.includes(preference)
          ? prev.dietary_preferences.filter(p => p !== preference)
          : [...prev.dietary_preferences, preference]
      }));
    }
  };

  const addMealEntry = (date?: string, mealType?: string) => {
    const newEntry: MealPlanEntryCreate = {
      recipe_id: 0,
      date: date || formData.start_date,
      meal_type: mealType || 'breakfast',
      servings: 1
    };
    setFormData(prev => ({
      ...prev,
      entries: [...prev.entries, newEntry]
    }));
    setIsDirty(true);
  };

  const updateMealEntry = <K extends keyof MealPlanEntryCreate>(index: number, field: K, value: MealPlanEntryCreate[K]) => {
    setFormData(prev => ({
      ...prev,
      entries: prev.entries.map((entry, i) =>
        i === index ? { ...entry, [field]: value } : entry
      )
    }));
    setIsDirty(true);
  };

  const removeMealEntry = (index: number) => {
    setFormData(prev => ({
      ...prev,
      entries: prev.entries.filter((_, i) => i !== index)
    }));
    setIsDirty(true);
  };

  // Re-roll a single meal: ask the backend for another recipe for this slot, using the
  // same weighted selection as plan generation. Avoids the current recipe and recipes
  // already used twice elsewhere in the plan. Updates local state only (saved on submit).
  const rerollMealEntry = async (index: number) => {
    const entry = formData.entries[index];
    if (!entry || rerollingIndex !== null) return;

    // All recipe ids used in the rest of the plan (every other slot), so the backend can
    // enforce the max-2-uses cap.
    const planRecipeIds = formData.entries
      .filter((e, i) => i !== index && e.recipe_id > 0)
      .map(e => e.recipe_id);

    setRerollingIndex(index);
    try {
      const recipe = await suggestMeal({
        meal_type: entry.meal_type,
        target_calories: formData.target_calories,
        current_recipe_id: entry.recipe_id > 0 ? entry.recipe_id : undefined,
        plan_recipe_ids: planRecipeIds,
      });
      updateMealEntry(index, 'recipe_id', recipe.id);
    } catch (error) {
      console.error('Failed to re-roll meal:', error);
    } finally {
      setRerollingIndex(null);
    }
  };

  // Group entries by date and meal type for organized display
  const groupEntriesByDateAndMeal = () => {
    if (!formData.start_date || !formData.end_date) return { grouped: {}, dates: [] };

    const grouped: Record<string, Record<string, Array<MealPlanEntryCreate & { originalIndex: number }>>> = {};

    // Create date range
    const startDate = new Date(formData.start_date);
    const endDate = new Date(formData.end_date);
    const dates: string[] = [];

    for (let d = new Date(startDate); d <= endDate; d.setDate(d.getDate() + 1)) {
      const dateStr = d.toISOString().split('T')[0];
      dates.push(dateStr);
      grouped[dateStr] = {
        breakfast: [],
        lunch: [],
        dinner: [],
        snack: []
      };
    }

    // Group existing entries with their original indices
    formData.entries.forEach((entry, originalIndex) => {
      if (grouped[entry.date] && grouped[entry.date][entry.meal_type]) {
        grouped[entry.date][entry.meal_type].push({ ...entry, originalIndex });
      }
    });

    return { grouped, dates };
  };

  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleDateString(getLocaleFromLanguage(i18n.language), {
      weekday: 'long',
      month: 'short',
      day: 'numeric'
    });
  };

  // Get recipe name from editing meal plan data if available
  const getRecipeName = (recipeId: number): string => {
    if (isEditing && editingMealPlan) {
      const entry = editingMealPlan.entries.find(e => e.recipe_id === recipeId);
      if (entry && entry.recipe) {
        return entry.recipe.name;
      }
    }
    if (generatedMealPlan) {
      const entry = generatedMealPlan.entries.find(e => e.recipe_id === recipeId);
      if (entry && entry.recipe) {
        return entry.recipe.name;
      }
    }
    return '';
  };

  // Get recipe IDs to exclude from suggestions (recipes already used on the same day)
  const getExcludeIdsForDate = (date: string, currentEntryIndex: number): number[] => {
    return formData.entries
      .filter((entry, idx) => 
        entry.date === date && 
        idx !== currentEntryIndex && 
        entry.recipe_id > 0
      )
      .map(entry => entry.recipe_id);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    try {
      if (isAutoGenerate && !isEditing) {
        const generated = await autoGenerate({
          ...autoGenerateData,
          start_date: autoGenerateData.start_date + 'T00:00:00',
        });

        setGeneratedMealPlan(generated);
        setIsAutoGenerate(false);

        const startDate = generated.start_date.split('T')[0];
        const endDate = generated.end_date.split('T')[0];

        setFormData({
          start_date: startDate,
          end_date: endDate,
          people_count: generated.people_count,
          target_calories: generated.target_calories,
          dietary_preferences: [...generated.dietary_preferences],
          entries: generated.entries.map(entry => ({
            recipe_id: entry.recipe_id,
            date: entry.date.split('T')[0],
            meal_type: entry.meal_type,
            servings: entry.servings
          }))
        });

        onSuccess();
      } else {
        const mealPlanData = {
          ...formData,
          start_date: formData.start_date + 'T00:00:00',
          end_date: formData.end_date + 'T23:59:59',
          // Drop empty meal slots (rows added but never assigned a recipe).
          // recipe_id 0 has no matching recipe and would fail the backend FK constraint.
          entries: formData.entries
            .filter(entry => entry.recipe_id > 0)
            .map(entry => ({
              ...entry,
              date: entry.date + 'T00:00:00'
            }))
        };

        if (isEditing && editingMealPlan) {
          await updatePlan(editingMealPlan.id, mealPlanData);
        } else {
          await createPlan(mealPlanData);
        }

        // Clear draft on successful save
        clearDraft();
        setIsDirty(false);
        
        onSuccess();
        onClose();

        if (!isEditing && !generatedMealPlan) {
          const defaultStartDate = getNextWeekMonday();
          const defaultEndDate = getSundayFromMonday(defaultStartDate);
          setFormData({
            start_date: defaultStartDate,
            end_date: defaultEndDate,
            people_count: 2,
            target_calories: 2000,
            dietary_preferences: [],
            entries: []
          });
          setAutoGenerateData({
            start_date: defaultStartDate,
            days: 7,
            target_calories: 2000,
            people_count: 2,
            dietary_preferences: [],
            user_id: 1
          });
        }
      }
    } catch (error) {
      console.error(`Failed to ${isEditing ? 'update' : 'create'} meal plan:`, error);
    }
  };

  const handleCloseAttempt = () => {
    // If dirty, show confirmation (for both new and editing modes)
    if (isDirty) {
      setShowCloseConfirm(true);
      return;
    }
    performClose();
  };

  const performClose = (discardDraft = false) => {
    if (discardDraft) {
      clearDraft();
    }
    
    onClose();
    if (!isEditing && !generatedMealPlan) {
      setFormData(getDefaultFormData());
      setAutoGenerateData(getDefaultAutoGenerateData());
    }
    setGeneratedMealPlan(null);
    setIsDirty(false);
    setShowCloseConfirm(false);
    setShowDraftRestorePrompt(false);
    setSavedDraft(null);
  };

  const handleConfirmClose = (saveDraftBeforeClose: boolean) => {
    if (saveDraftBeforeClose) {
      saveDraft();
    } else {
      clearDraft();
    }
    setShowCloseConfirm(false);
    performClose(!saveDraftBeforeClose);
  };

  // Handle switching to auto-generate mode - confirm if there are entries
  const handleSwitchToAutoGenerate = () => {
    if (formData.entries.length > 0 || isDirty) {
      setShowRegenerateConfirm(true);
    } else {
      setIsAutoGenerate(true);
    }
  };

  // Confirm switching to auto-generate (will lose manual entries)
  const confirmSwitchToAutoGenerate = () => {
    setShowRegenerateConfirm(false);
    setFormData(prev => ({ ...prev, entries: [] }));
    setIsAutoGenerate(true);
    setIsDirty(false);
  };

  // Handle regenerate request - confirm if there are modifications to the generated plan
  const handleRegenerateRequest = () => {
    if (isDirty) {
      setShowRegenerateConfirm(true);
    } else {
      performRegenerate();
    }
  };

  // Perform regeneration - go back to auto-generate mode
  const performRegenerate = () => {
    setShowRegenerateConfirm(false);
    setGeneratedMealPlan(null);
    setIsAutoGenerate(true);
    setIsDirty(false);
  };

  if (!isOpen) return null;

  const isLoading = creating || updating || autoGenerating;
  const { grouped, dates } = groupEntriesByDateAndMeal();

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div className="bg-white rounded-lg shadow-xl max-w-6xl w-full max-h-[90vh] overflow-y-auto">
        <div className="flex items-center justify-between p-6 border-b border-neutral-200">
          <h2 className="text-xl font-semibold text-neutral-900">
            {isEditing ? t('mealPlans.editMealPlan') : generatedMealPlan ? t('mealPlans.reviewGeneratedPlan') : t('mealPlans.createMealPlan')}
          </h2>
          <button
            onClick={handleCloseAttempt}
            className="text-neutral-400 hover:text-neutral-600 transition-colors"
            data-testid="modal-close-button"
          >
            <X className="h-6 w-6" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="p-6 space-y-6">
          {/* Draft Restore Prompt */}
          {showDraftRestorePrompt && savedDraft && (
            <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 mb-4">
              <div className="flex items-start gap-3">
                <AlertTriangle className="h-5 w-5 text-amber-600 flex-shrink-0 mt-0.5" />
                <div className="flex-1">
                  <p className="text-sm font-medium text-amber-800">
                    {t('mealPlans.draft.unsavedDraftFound')}
                  </p>
                  <p className="text-sm text-amber-700 mt-1">
                    {t('mealPlans.draft.draftFoundMessage', { date: new Date(savedDraft.savedAt).toLocaleString(getLocaleFromLanguage(i18n.language)) })}
                  </p>
                  <div className="flex gap-2 mt-3">
                    <Button
                      type="button"
                      size="sm"
                      onClick={() => restoreDraft(savedDraft)}
                    >
                      {t('mealPlans.draft.restoreDraft')}
                    </Button>
                    <Button
                      type="button"
                      variant="outline"
                      size="sm"
                      onClick={declineDraftRestore}
                    >
                      {t('common.discard')}
                    </Button>
                  </div>
                </div>
              </div>
            </div>
          )}

          {generatedMealPlan && (
            <div className="bg-green-50 border border-green-200 rounded-lg p-4 mb-4">
              <div className="flex items-center justify-between">
                <p className="text-sm text-green-800">
                  {t('mealPlans.generated.successMessage')}
                </p>
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  onClick={handleRegenerateRequest}
                  className="ml-4 flex-shrink-0"
                >
                  {t('mealPlans.detail.regenerate')}
                </Button>
              </div>
            </div>
          )}

          {/* Mode Toggle - Only show for new meal plans */}
          {!isEditing && !generatedMealPlan && (
            <div className="flex space-x-4 mb-6">
              <button
                type="button"
                onClick={() => setIsAutoGenerate(false)}
                className={`px-4 py-2 rounded-md font-medium transition-colors ${!isAutoGenerate
                  ? 'bg-primary-600 text-white'
                  : 'bg-neutral-100 text-neutral-700 hover:bg-neutral-200'
                  }`}
              >
                {t('mealPlans.form.manualPlanning')}
              </button>
              <button
                type="button"
                onClick={handleSwitchToAutoGenerate}
                className={`px-4 py-2 rounded-md font-medium transition-colors ${isAutoGenerate
                  ? 'bg-primary-600 text-white'
                  : 'bg-neutral-100 text-neutral-700 hover:bg-neutral-200'
                  }`}
              >
                {t('mealPlans.form.autoGenerate')}
              </button>
            </div>
          )}

          {isAutoGenerate && !isEditing ? (
            /* Auto Generate Form */
            <div className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <Input
                  label={t('mealPlans.form.startDate')}
                  type="date"
                  value={autoGenerateData.start_date}
                  onChange={(e) => handleAutoGenerateChange('start_date', e.target.value)}
                  leftIcon={<Calendar className="h-5 w-5" />}
                  required
                  fullWidth
                />

                <NumericInput
                  label={t('mealPlans.form.numberOfDays')}
                  value={autoGenerateData.days}
                  onChange={(val) => handleAutoGenerateChange('days', val)}
                  min={1}
                  max={30}
                  required
                  fullWidth
                />
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <NumericInput
                  label={t('mealPlans.form.peopleCount')}
                  value={autoGenerateData.people_count}
                  onChange={(val) => handleAutoGenerateChange('people_count', val)}
                  leftIcon={<Users className="h-5 w-5" />}
                  min={1}
                  max={20}
                  required
                  fullWidth
                />

                <NumericInput
                  label={t('mealPlans.form.targetCaloriesPerDay')}
                  value={autoGenerateData.target_calories}
                  onChange={(val) => handleAutoGenerateChange('target_calories', val)}
                  leftIcon={<Target className="h-5 w-5" />}
                  min={1000}
                  max={5000}
                  step={100}
                  required
                  fullWidth
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-neutral-700 mb-2">
                  {t('mealPlans.form.dietaryPreferences')}
                </label>
                <div className="flex flex-wrap gap-2">
                  {dietaryOptions.map((option) => (
                    <button
                      key={option.value}
                      type="button"
                      onClick={() => toggleDietaryPreference(option.value)}
                      className={`
                        inline-flex items-center rounded-full px-3 py-1 text-sm font-medium transition-colors
                        ${autoGenerateData.dietary_preferences.includes(option.value)
                          ? 'bg-primary-100 text-primary-800'
                          : 'bg-neutral-100 text-neutral-700 hover:bg-neutral-200'
                        }
                      `}
                    >
                      {option.label}
                    </button>
                  ))}
                </div>
              </div>

              <Card className="bg-neutral-50 border-neutral-200">
                <CardContent className="pt-4">
                    <p className="text-sm text-neutral-600">
                      <Trans
                        i18nKey="mealPlans.autoGenerate.summaryTemplate"
                        values={{
                          days: autoGenerateData.days || '...',
                          startDate: autoGenerateData.start_date ? formatDate(autoGenerateData.start_date) : '...'
                        }}
                        components={{ strong: <strong /> }}
                      />
                    </p>
                </CardContent>
              </Card>
            </div>
          ) : (
            /* Manual Form */
            <div className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <Input
                  label={t('mealPlans.form.startDate')}
                  type="date"
                  value={formData.start_date}
                  onChange={(e) => handleInputChange('start_date', e.target.value)}
                  leftIcon={<Calendar className="h-5 w-5" />}
                  required
                  fullWidth
                />

                <Input
                  label={t('mealPlans.form.endDate')}
                  type="date"
                  value={formData.end_date}
                  onChange={(e) => handleInputChange('end_date', e.target.value)}
                  leftIcon={<Calendar className="h-5 w-5" />}
                  required
                  fullWidth
                />
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <NumericInput
                  label={t('mealPlans.form.peopleCount')}
                  value={formData.people_count}
                  onChange={(val) => handleInputChange('people_count', val)}
                  leftIcon={<Users className="h-5 w-5" />}
                  min={1}
                  max={20}
                  required
                  fullWidth
                />

                <NumericInput
                  label={t('mealPlans.form.targetCaloriesPerDay')}
                  value={formData.target_calories}
                  onChange={(val) => handleInputChange('target_calories', val)}
                  leftIcon={<Target className="h-5 w-5" />}
                  min={1000}
                  max={5000}
                  step={100}
                  required
                  fullWidth
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-neutral-700 mb-2">
                  {t('mealPlans.form.dietaryPreferences')}
                </label>
                <div className="flex flex-wrap gap-2">
                  {dietaryOptions.map((option) => (
                    <button
                      key={option.value}
                      type="button"
                      onClick={() => toggleDietaryPreference(option.value)}
                      className={`
                        inline-flex items-center rounded-full px-3 py-1 text-sm font-medium transition-colors
                        ${formData.dietary_preferences.includes(option.value)
                          ? 'bg-primary-100 text-primary-800'
                          : 'bg-neutral-100 text-neutral-700 hover:bg-neutral-200'
                        }
                      `}
                    >
                      {option.label}
                    </button>
                  ))}
                </div>
              </div>

              {formData.start_date && formData.end_date && (
                <Card className="bg-neutral-50 border-neutral-200">
                  <CardContent className="pt-4">
                    <p className="text-sm text-neutral-600">
                      <Trans
                        i18nKey="mealPlans.autoGenerate.planningDays"
                        values={{
                          days: dates.length,
                          startDate: formatDate(formData.start_date),
                          endDate: formatDate(formData.end_date)
                        }}
                        components={{ strong: <strong /> }}
                      />
                    </p>
                  </CardContent>
                </Card>
              )}

              {/* Meal Schedule - Organized by Day and Meal Type */}
              {formData.start_date && formData.end_date && (
                <div>
                  <div className="flex items-center justify-between mb-4">
                    <h3 className="text-lg font-medium text-neutral-900">{t('mealPlans.form.mealSchedule')}</h3>
                    <Button
                      type="button"
                      variant="outline"
                      size="sm"
                      onClick={() => addMealEntry()}
                      leftIcon={<Plus className="h-4 w-4" />}
                    >
                      {t('mealPlans.form.addMeal')}
                    </Button>
                  </div>

                  <div className="space-y-6">
                    {dates.map((date) => (
                      <Card key={date} allowOverflow>
                        <CardHeader>
                          <CardTitle className="text-base">{formatDate(date)}</CardTitle>
                        </CardHeader>
                        <CardContent className="space-y-4">
                          {['breakfast', 'lunch', 'dinner', 'snack'].map((mealType) => (
                            <div key={mealType} className="border-l-4 border-primary-200 pl-4">
                              <div className="flex items-center justify-between mb-2">
                                <h4 className="font-medium text-neutral-700 capitalize">{t(`mealPlans.mealTypes.${mealType}`)}</h4>
                                <Button
                                  type="button"
                                  variant="ghost"
                                  size="sm"
                                  onClick={() => addMealEntry(date, mealType)}
                                  className="text-xs"
                                >
                                  <Plus className="h-3 w-3 mr-1" />
                                  {t('common.add')}
                                </Button>
                              </div>

                              {grouped[date][mealType].length === 0 ? (
                                <div className="text-sm text-neutral-400 italic">{t('mealPlans.noMealsPlanned')}</div>
                              ) : (
                                <div className="space-y-2">
                                  {grouped[date][mealType].map((entry) => (
                                    <div key={entry.originalIndex} className="bg-neutral-50 rounded-lg p-3">
                                      <div className="grid grid-cols-12 gap-3 items-end">
                                        {/* Recipe Selection - Takes up most space */}
                                        <div className="col-span-12 md:col-span-6">
                                          <label className="block text-xs font-medium text-neutral-700 mb-1">
                                            {t('mealPlans.form.recipe')}
                                          </label>
                                          <RecipeSearchSelect
                                            value={entry.recipe_id}
                                            onChange={(recipeId) => updateMealEntry(entry.originalIndex, 'recipe_id', recipeId)}
                                            placeholder={t('mealPlans.form.searchForRecipe')}
                                            initialDisplayName={getRecipeName(entry.recipe_id)}
                                            mealType={['breakfast', 'lunch', 'dinner'].includes(mealType) ? mealType as 'breakfast' | 'lunch' | 'dinner' : undefined}
                                            excludeIds={getExcludeIdsForDate(date, entry.originalIndex)}
                                          />
                                        </div>

                                        {/* Servings */}
                                        <div className="col-span-6 md:col-span-3">
                                          <NumericInput
                                            label={t('mealPlans.form.servings')}
                                            value={entry.servings}
                                            onChange={(val) => updateMealEntry(entry.originalIndex, 'servings', val)}
                                            min={1}
                                            max={20}
                                            fullWidth
                                          />
                                        </div>

                                        {/* Re-roll + Delete Buttons */}
                                        <div className="col-span-6 md:col-span-3 flex gap-2">
                                          <Button
                                            type="button"
                                            variant="outline"
                                            size="sm"
                                            onClick={() => rerollMealEntry(entry.originalIndex)}
                                            isLoading={rerollingIndex === entry.originalIndex}
                                            disabled={rerollingIndex !== null}
                                            title={t('mealPlans.form.rerollMeal')}
                                            aria-label={t('mealPlans.form.rerollMeal')}
                                            className="flex-1 text-primary-600 hover:text-primary-700 h-[42px] px-2"
                                          >
                                            {rerollingIndex === entry.originalIndex ? null : <Dices className="h-4 w-4" />}
                                          </Button>
                                          <Button
                                            type="button"
                                            variant="outline"
                                            size="sm"
                                            onClick={() => removeMealEntry(entry.originalIndex)}
                                            className="flex-1 text-error-600 hover:text-error-700 h-[42px] px-2"
                                          >
                                            <Trash2 className="h-3 w-3" />
                                          </Button>
                                        </div>
                                      </div>
                                    </div>
                                  ))}
                                </div>
                              )}
                            </div>
                          ))}
                        </CardContent>
                      </Card>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}

          {/* Form Actions */}
          <div className="flex justify-end space-x-3 pt-6 border-t border-neutral-200">
            <Button type="button" variant="outline" onClick={handleCloseAttempt}>
              {generatedMealPlan ? t('common.close') : t('common.cancel')}
            </Button>
            <Button
              type="submit"
              isLoading={isLoading}
              disabled={
                isAutoGenerate && !isEditing
                  ? !autoGenerateData.start_date || autoGenerateData.days < 1
                  : !formData.start_date || !formData.end_date
              }
            >
              {isEditing
                ? t('mealPlans.updateMealPlan')
                : generatedMealPlan
                  ? t('mealPlans.saveMealPlan')
                  : isAutoGenerate
                    ? t('mealPlans.generateMealPlan')
                    : t('mealPlans.createMealPlan')
              }
            </Button>
          </div>
        </form>
      </div>

      {/* Close Confirmation Dialog */}
      {showCloseConfirm && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-[60]">
          <div className="bg-white rounded-lg shadow-xl max-w-md w-full p-6">
            <div className="flex items-start gap-3">
              <AlertTriangle className="h-6 w-6 text-amber-500 flex-shrink-0" />
              <div className="flex-1">
                <h3 className="text-lg font-semibold text-neutral-900">{t('mealPlans.draft.unsavedChanges')}</h3>
                <p className="text-sm text-neutral-600 mt-2">
                  {isEditing
                    ? t('mealPlans.draft.unsavedChangesEditMessage')
                    : t('mealPlans.draft.unsavedChangesNewMessage')
                  }
                </p>
              </div>
            </div>
            <div className="flex justify-end gap-2 mt-6">
              <Button
                type="button"
                variant="outline"
                onClick={() => setShowCloseConfirm(false)}
              >
                {t('mealPlans.draft.continueEditing')}
              </Button>
              <Button
                type="button"
                variant="outline"
                onClick={() => handleConfirmClose(false)}
                className="text-error-600 border-error-300 hover:bg-error-50"
              >
                {t('common.discard')}
              </Button>
              {!isEditing && (
                <Button
                  type="button"
                  onClick={() => handleConfirmClose(true)}
                >
                  {t('mealPlans.draft.saveDraft')}
                </Button>
              )}
            </div>
          </div>
        </div>
      )}

      {/* Regenerate/Switch Mode Confirmation Dialog */}
      {showRegenerateConfirm && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-[60]">
          <div className="bg-white rounded-lg shadow-xl max-w-md w-full p-6">
            <div className="flex items-start gap-3">
              <AlertTriangle className="h-6 w-6 text-amber-500 flex-shrink-0" />
              <div className="flex-1">
                <h3 className="text-lg font-semibold text-neutral-900">
                  {generatedMealPlan ? t('mealPlans.regenerateConfirm.regenerateMealPlan') : t('mealPlans.regenerateConfirm.switchToAutoGenerate')}
                </h3>
                <p className="text-sm text-neutral-600 mt-2">
                  {generatedMealPlan
                    ? t('mealPlans.regenerateConfirm.regenerateMessage')
                    : t('mealPlans.regenerateConfirm.switchMessage')
                  }
                </p>
              </div>
            </div>
            <div className="flex justify-end gap-2 mt-6">
              <Button
                type="button"
                variant="outline"
                onClick={() => setShowRegenerateConfirm(false)}
              >
                {t('common.cancel')}
              </Button>
              <Button
                type="button"
                onClick={generatedMealPlan ? performRegenerate : confirmSwitchToAutoGenerate}
                className="bg-amber-600 hover:bg-amber-700"
              >
                {generatedMealPlan ? t('mealPlans.detail.regenerate') : t('mealPlans.regenerateConfirm.switchToAutoGenerate')}
              </Button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default CreateMealPlanModal;
