import React, { useState, useEffect } from 'react';
import { X, Calendar, Users, Target, Plus, Trash2 } from 'lucide-react';
import { MealPlanCreate, MealPlanEntryCreate, MealPlan } from '../../types';
import Button from '../ui/Button';
import Input from '../ui/Input';
import Card, { CardContent, CardHeader, CardTitle } from '../ui/Card';
import RecipeSearchSelect from '../recipes/RecipeSearchSelect';
import useApi from '../../hooks/useApi';
import { createMealPlan, autoGenerateMealPlan, updateMealPlan } from '../../api/mealPlanApi';

const getNextWeekMonday = (): string => {
  const today = new Date();
  const dayOfWeek = today.getDay();
  const daysUntilMonday = (8 - dayOfWeek) % 7 || 7;
  const nextMonday = new Date(today);
  nextMonday.setDate(today.getDate() + daysUntilMonday);
  return nextMonday.toISOString().split('T')[0];
};

const getSundayFromMonday = (mondayDate: string): string => {
  const monday = new Date(mondayDate);
  const sunday = new Date(monday);
  sunday.setDate(monday.getDate() + 6);
  return sunday.toISOString().split('T')[0];
};

interface CreateMealPlanModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess: () => void;
  editingMealPlan?: MealPlan | null;
}

const nextMonday = getNextWeekMonday();

const CreateMealPlanModal: React.FC<CreateMealPlanModalProps> = ({
  isOpen,
  onClose,
  onSuccess,
  editingMealPlan = null
}) => {
  const isEditing = !!editingMealPlan;
  const [isAutoGenerate, setIsAutoGenerate] = useState(false);
  const [generatedMealPlan, setGeneratedMealPlan] = useState<MealPlan | null>(null);
  const [formData, setFormData] = useState<MealPlanCreate>({
    start_date: nextMonday,
    end_date: getSundayFromMonday(nextMonday),
    people_count: 2,
    target_calories: 2000,
    dietary_preferences: [],
    entries: []
  });

  type AutoGenerateData = {
    start_date: string;
    days: number;
    target_calories: number;
    people_count: number;
    dietary_preferences: string[];
    user_id: number;
  };

  const [autoGenerateData, setAutoGenerateData] = useState<AutoGenerateData>({
    start_date: nextMonday,
    days: 7,
    target_calories: 2000,
    people_count: 2,
    dietary_preferences: [],
    user_id: 1
  });

  const { loading: creating, execute: createPlan } = useApi(createMealPlan);
  const { loading: updating, execute: updatePlan } = useApi(updateMealPlan);
  const { loading: autoGenerating, execute: autoGenerate } = useApi(autoGenerateMealPlan);

  // Initialize form data when editing meal plan changes
  useEffect(() => {
    if (editingMealPlan) {
      const startDate = editingMealPlan.start_date.split('T')[0];
      const endDate = editingMealPlan.end_date.split('T')[0];

      setFormData({
        start_date: startDate,
        end_date: endDate,
        people_count: editingMealPlan.people_count,
        target_calories: editingMealPlan.target_calories,
        dietary_preferences: [...editingMealPlan.dietary_preferences],
        entries: editingMealPlan.entries.map(entry => ({
          recipe_id: entry.recipe_id,
          date: entry.date.split('T')[0],
          meal_type: entry.meal_type,
          servings: entry.servings
        }))
      });

      // Disable auto-generate mode when editing
      setIsAutoGenerate(false);
    } else if (generatedMealPlan) {
      const startDate = generatedMealPlan.start_date.split('T')[0];
      const endDate = generatedMealPlan.end_date.split('T')[0];

      setFormData({
        start_date: startDate,
        end_date: endDate,
        people_count: generatedMealPlan.people_count,
        target_calories: generatedMealPlan.target_calories,
        dietary_preferences: [...generatedMealPlan.dietary_preferences],
        entries: generatedMealPlan.entries.map(entry => ({
          recipe_id: entry.recipe_id,
          date: entry.date.split('T')[0],
          meal_type: entry.meal_type,
          servings: entry.servings
        }))
      });

      setIsAutoGenerate(false);
    } else {
      const defaultStartDate = getNextWeekMonday();
      const defaultEndDate = getSundayFromMonday(defaultStartDate);
      setFormData({
        start_date: defaultStartDate,
        end_date: defaultEndDate,
        people_count: 2,
        target_calories: 2000,
        dietary_preferences: [],
        entries: []
      });
      setAutoGenerateData({
        start_date: defaultStartDate,
        days: 7,
        target_calories: 2000,
        people_count: 2,
        dietary_preferences: [],
        user_id: 1
      });
    }
  }, [editingMealPlan, generatedMealPlan]);

  const dietaryOptions = [
    { value: 'vegetarian', label: 'Vegetarian' },
    { value: 'vegan', label: 'Vegan' },
    { value: 'gluten-free', label: 'Gluten Free' },
    { value: 'dairy-free', label: 'Dairy Free' },
    { value: 'keto', label: 'Keto' },
    { value: 'low-carb', label: 'Low Carb' },
    { value: 'high-protein', label: 'High Protein' },
  ];

  const handleInputChange = <K extends keyof MealPlanCreate>(field: K, value: MealPlanCreate[K]) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  // Helper function to handle numeric input changes
  const handleNumericInputChange = (field: keyof MealPlanCreate, stringValue: string) => {
    if (stringValue === '') {
      setFormData(prev => ({ ...prev, [field]: 0 }));
      return;
    }
    const numValue = Number(stringValue);
    if (!isNaN(numValue)) {
      setFormData(prev => ({ ...prev, [field]: numValue }));
    }
  };

  const handleAutoGenerateChange = <K extends keyof AutoGenerateData>(field: K, value: AutoGenerateData[K]) => {
    setAutoGenerateData(prev => ({ ...prev, [field]: value }));
  };

  // Helper function for numeric auto-generate input changes
  const handleAutoGenerateNumericChange = (field: keyof AutoGenerateData, stringValue: string) => {
    if (stringValue === '') {
      setAutoGenerateData(prev => ({ ...prev, [field]: 0 }));
      return;
    }
    const numValue = Number(stringValue);
    if (!isNaN(numValue)) {
      setAutoGenerateData(prev => ({ ...prev, [field]: numValue }));
    }
  };

  const toggleDietaryPreference = (preference: string) => {
    if (isAutoGenerate) {
      setAutoGenerateData(prev => ({
        ...prev,
        dietary_preferences: prev.dietary_preferences.includes(preference)
          ? prev.dietary_preferences.filter(p => p !== preference)
          : [...prev.dietary_preferences, preference]
      }));
    } else {
      setFormData(prev => ({
        ...prev,
        dietary_preferences: prev.dietary_preferences.includes(preference)
          ? prev.dietary_preferences.filter(p => p !== preference)
          : [...prev.dietary_preferences, preference]
      }));
    }
  };

  const addMealEntry = (date?: string, mealType?: string) => {
    const newEntry: MealPlanEntryCreate = {
      recipe_id: 0,
      date: date || formData.start_date,
      meal_type: mealType || 'breakfast',
      servings: 1
    };
    setFormData(prev => ({
      ...prev,
      entries: [...prev.entries, newEntry]
    }));
  };

  const updateMealEntry = <K extends keyof MealPlanEntryCreate>(index: number, field: K, value: MealPlanEntryCreate[K]) => {
    setFormData(prev => ({
      ...prev,
      entries: prev.entries.map((entry, i) =>
        i === index ? { ...entry, [field]: value } : entry
      )
    }));
  };

  // Helper function for numeric meal entry fields
  const updateMealEntryNumeric = (index: number, field: keyof MealPlanEntryCreate, stringValue: string) => {
    if (stringValue === '') {
      updateMealEntry(index, field, 0 as MealPlanEntryCreate[typeof field]);
      return;
    }
    const numValue = Number(stringValue);
    if (!isNaN(numValue)) {
      updateMealEntry(index, field, numValue as MealPlanEntryCreate[typeof field]);
    }
  };

  const removeMealEntry = (index: number) => {
    setFormData(prev => ({
      ...prev,
      entries: prev.entries.filter((_, i) => i !== index)
    }));
  };

  // Group entries by date and meal type for organized display
  const groupEntriesByDateAndMeal = () => {
    if (!formData.start_date || !formData.end_date) return { grouped: {}, dates: [] };

    const grouped: Record<string, Record<string, Array<MealPlanEntryCreate & { originalIndex: number }>>> = {};

    // Create date range
    const startDate = new Date(formData.start_date);
    const endDate = new Date(formData.end_date);
    const dates: string[] = [];

    for (let d = new Date(startDate); d <= endDate; d.setDate(d.getDate() + 1)) {
      const dateStr = d.toISOString().split('T')[0];
      dates.push(dateStr);
      grouped[dateStr] = {
        breakfast: [],
        lunch: [],
        dinner: [],
        snack: []
      };
    }

    // Group existing entries with their original indices
    formData.entries.forEach((entry, originalIndex) => {
      if (grouped[entry.date] && grouped[entry.date][entry.meal_type]) {
        grouped[entry.date][entry.meal_type].push({ ...entry, originalIndex });
      }
    });

    return { grouped, dates };
  };

  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', {
      weekday: 'long',
      month: 'short',
      day: 'numeric'
    });
  };

  // Get recipe name from editing meal plan data if available
  const getRecipeName = (recipeId: number): string => {
    if (isEditing && editingMealPlan) {
      const entry = editingMealPlan.entries.find(e => e.recipe_id === recipeId);
      if (entry && entry.recipe) {
        return entry.recipe.name;
      }
    }
    if (generatedMealPlan) {
      const entry = generatedMealPlan.entries.find(e => e.recipe_id === recipeId);
      if (entry && entry.recipe) {
        return entry.recipe.name;
      }
    }
    return '';
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    try {
      if (isAutoGenerate && !isEditing) {
        const generated = await autoGenerate({
          ...autoGenerateData,
          start_date: autoGenerateData.start_date + 'T00:00:00',
        });

        setGeneratedMealPlan(generated);
        setIsAutoGenerate(false);

        const startDate = generated.start_date.split('T')[0];
        const endDate = generated.end_date.split('T')[0];

        setFormData({
          start_date: startDate,
          end_date: endDate,
          people_count: generated.people_count,
          target_calories: generated.target_calories,
          dietary_preferences: [...generated.dietary_preferences],
          entries: generated.entries.map(entry => ({
            recipe_id: entry.recipe_id,
            date: entry.date.split('T')[0],
            meal_type: entry.meal_type,
            servings: entry.servings
          }))
        });

        onSuccess();
      } else {
        const mealPlanData = {
          ...formData,
          start_date: formData.start_date + 'T00:00:00',
          end_date: formData.end_date + 'T23:59:59',
          entries: formData.entries.map(entry => ({
            ...entry,
            date: entry.date + 'T00:00:00'
          }))
        };

        if (isEditing && editingMealPlan) {
          await updatePlan(editingMealPlan.id, mealPlanData);
        } else {
          await createPlan(mealPlanData);
        }

        onSuccess();
        onClose();

        if (!isEditing && !generatedMealPlan) {
          const defaultStartDate = getNextWeekMonday();
          const defaultEndDate = getSundayFromMonday(defaultStartDate);
          setFormData({
            start_date: defaultStartDate,
            end_date: defaultEndDate,
            people_count: 2,
            target_calories: 2000,
            dietary_preferences: [],
            entries: []
          });
          setAutoGenerateData({
            start_date: defaultStartDate,
            days: 7,
            target_calories: 2000,
            people_count: 2,
            dietary_preferences: [],
            user_id: 1
          });
        }
      }
    } catch (error) {
      console.error(`Failed to ${isEditing ? 'update' : 'create'} meal plan:`, error);
    }
  };

  const handleClose = () => {
    onClose();
    if (!isEditing && !generatedMealPlan) {
      const defaultStartDate = getNextWeekMonday();
      const defaultEndDate = getSundayFromMonday(defaultStartDate);
      setFormData({
        start_date: defaultStartDate,
        end_date: defaultEndDate,
        people_count: 2,
        target_calories: 2000,
        dietary_preferences: [],
        entries: []
      });
      setAutoGenerateData({
        start_date: defaultStartDate,
        days: 7,
        target_calories: 2000,
        people_count: 2,
        dietary_preferences: [],
        user_id: 1
      });
    }
    setGeneratedMealPlan(null);
  };

  if (!isOpen) return null;

  const isLoading = creating || updating || autoGenerating;
  const { grouped, dates } = groupEntriesByDateAndMeal();

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div className="bg-white rounded-lg shadow-xl max-w-6xl w-full max-h-[90vh] overflow-y-auto">
        <div className="flex items-center justify-between p-6 border-b border-neutral-200">
          <h2 className="text-xl font-semibold text-neutral-900">
            {isEditing ? 'Edit Meal Plan' : generatedMealPlan ? 'Review Generated Plan' : 'Create Meal Plan'}
          </h2>
          <button
            onClick={handleClose}
            className="text-neutral-400 hover:text-neutral-600 transition-colors"
          >
            <X className="h-6 w-6" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="p-6 space-y-6">
          {generatedMealPlan && (
            <div className="bg-green-50 border border-green-200 rounded-lg p-4 mb-4">
              <p className="text-sm text-green-800">
                Meal plan generated successfully! Review and customize the meals below, then click "Save Meal Plan" to keep your changes.
              </p>
            </div>
          )}

          {/* Mode Toggle - Only show for new meal plans */}
          {!isEditing && !generatedMealPlan && (
            <div className="flex space-x-4 mb-6">
              <button
                type="button"
                onClick={() => setIsAutoGenerate(false)}
                className={`px-4 py-2 rounded-md font-medium transition-colors ${!isAutoGenerate
                    ? 'bg-primary-600 text-white'
                    : 'bg-neutral-100 text-neutral-700 hover:bg-neutral-200'
                  }`}
              >
                Manual Planning
              </button>
              <button
                type="button"
                onClick={() => setIsAutoGenerate(true)}
                className={`px-4 py-2 rounded-md font-medium transition-colors ${isAutoGenerate
                    ? 'bg-primary-600 text-white'
                    : 'bg-neutral-100 text-neutral-700 hover:bg-neutral-200'
                  }`}
              >
                Auto Generate
              </button>
            </div>
          )}

          {isAutoGenerate && !isEditing ? (
            /* Auto Generate Form */
            <div className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <Input
                  label="Start Date"
                  type="date"
                  value={autoGenerateData.start_date}
                  onChange={(e) => handleAutoGenerateChange('start_date', e.target.value)}
                  leftIcon={<Calendar className="h-5 w-5" />}
                  required
                  fullWidth
                />

                <Input
                  label="Number of Days"
                  type="number"
                  value={autoGenerateData.days}
                  onChange={(e) => handleAutoGenerateNumericChange('days', e.target.value)}
                  min={1}
                  max={30}
                  required
                  fullWidth
                />
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <Input
                  label="People Count"
                  type="number"
                  value={autoGenerateData.people_count}
                  onChange={(e) => handleAutoGenerateNumericChange('people_count', e.target.value)}
                  leftIcon={<Users className="h-5 w-5" />}
                  min={1}
                  max={20}
                  required
                  fullWidth
                />

                <Input
                  label="Target Calories per Day"
                  type="number"
                  value={autoGenerateData.target_calories}
                  onChange={(e) => handleAutoGenerateNumericChange('target_calories', e.target.value)}
                  leftIcon={<Target className="h-5 w-5" />}
                  min={1000}
                  max={5000}
                  step={100}
                  required
                  fullWidth
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-neutral-700 mb-2">
                  Dietary Preferences
                </label>
                <div className="flex flex-wrap gap-2">
                  {dietaryOptions.map((option) => (
                    <button
                      key={option.value}
                      type="button"
                      onClick={() => toggleDietaryPreference(option.value)}
                      className={`
                        inline-flex items-center rounded-full px-3 py-1 text-sm font-medium transition-colors
                        ${autoGenerateData.dietary_preferences.includes(option.value)
                          ? 'bg-primary-100 text-primary-800'
                          : 'bg-neutral-100 text-neutral-700 hover:bg-neutral-200'
                        }
                      `}
                    >
                      {option.label}
                    </button>
                  ))}
                </div>
              </div>

              <Card className="bg-neutral-50 border-neutral-200">
                <CardContent className="pt-4">
                  <p className="text-sm text-neutral-600">
                    This will generate a meal plan for <strong>{autoGenerateData.days} days</strong> starting from{' '}
                    <strong>{autoGenerateData.start_date ? formatDate(autoGenerateData.start_date) : '...'}</strong>.
                    The system will automatically select recipes based on your preferences and calorie goals.
                  </p>
                </CardContent>
              </Card>
            </div>
          ) : (
            /* Manual Form */
            <div className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <Input
                  label="Start Date"
                  type="date"
                  value={formData.start_date}
                  onChange={(e) => handleInputChange('start_date', e.target.value)}
                  leftIcon={<Calendar className="h-5 w-5" />}
                  required
                  fullWidth
                />

                <Input
                  label="End Date"
                  type="date"
                  value={formData.end_date}
                  onChange={(e) => handleInputChange('end_date', e.target.value)}
                  leftIcon={<Calendar className="h-5 w-5" />}
                  required
                  fullWidth
                />
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <Input
                  label="People Count"
                  type="number"
                  value={formData.people_count}
                  onChange={(e) => handleNumericInputChange('people_count', e.target.value)}
                  leftIcon={<Users className="h-5 w-5" />}
                  min={1}
                  max={20}
                  required
                  fullWidth
                />

                <Input
                  label="Target Calories per Day"
                  type="number"
                  value={formData.target_calories}
                  onChange={(e) => handleNumericInputChange('target_calories', e.target.value)}
                  leftIcon={<Target className="h-5 w-5" />}
                  min={1000}
                  max={5000}
                  step={100}
                  required
                  fullWidth
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-neutral-700 mb-2">
                  Dietary Preferences
                </label>
                <div className="flex flex-wrap gap-2">
                  {dietaryOptions.map((option) => (
                    <button
                      key={option.value}
                      type="button"
                      onClick={() => toggleDietaryPreference(option.value)}
                      className={`
                        inline-flex items-center rounded-full px-3 py-1 text-sm font-medium transition-colors
                        ${formData.dietary_preferences.includes(option.value)
                          ? 'bg-primary-100 text-primary-800'
                          : 'bg-neutral-100 text-neutral-700 hover:bg-neutral-200'
                        }
                      `}
                    >
                      {option.label}
                    </button>
                  ))}
                </div>
              </div>

              {formData.start_date && formData.end_date && (
                <Card className="bg-neutral-50 border-neutral-200">
                  <CardContent className="pt-4">
                    <p className="text-sm text-neutral-600">
                      Planning meals for <strong>{dates.length} days</strong> from{' '}
                      <strong>{formatDate(formData.start_date)}</strong> to{' '}
                      <strong>{formatDate(formData.end_date)}</strong>.
                    </p>
                  </CardContent>
                </Card>
              )}

              {/* Meal Schedule - Organized by Day and Meal Type */}
              {formData.start_date && formData.end_date && (
                <div>
                  <div className="flex items-center justify-between mb-4">
                    <h3 className="text-lg font-medium text-neutral-900">Meal Schedule</h3>
                    <Button
                      type="button"
                      variant="outline"
                      size="sm"
                      onClick={() => addMealEntry()}
                      leftIcon={<Plus className="h-4 w-4" />}
                    >
                      Add Meal
                    </Button>
                  </div>

                  <div className="space-y-6">
                    {dates.map((date) => (
                      <Card key={date}>
                        <CardHeader>
                          <CardTitle className="text-base">{formatDate(date)}</CardTitle>
                        </CardHeader>
                        <CardContent className="space-y-4">
                          {['breakfast', 'lunch', 'dinner', 'snack'].map((mealType) => (
                            <div key={mealType} className="border-l-4 border-primary-200 pl-4">
                              <div className="flex items-center justify-between mb-2">
                                <h4 className="font-medium text-neutral-700 capitalize">{mealType}</h4>
                                <Button
                                  type="button"
                                  variant="ghost"
                                  size="sm"
                                  onClick={() => addMealEntry(date, mealType)}
                                  className="text-xs"
                                >
                                  <Plus className="h-3 w-3 mr-1" />
                                  Add
                                </Button>
                              </div>

                              {grouped[date][mealType].length === 0 ? (
                                <div className="text-sm text-neutral-400 italic">No meals planned</div>
                              ) : (
                                <div className="space-y-2">
                                  {grouped[date][mealType].map((entry) => (
                                    <div key={entry.originalIndex} className="bg-neutral-50 rounded-lg p-3">
                                      <div className="grid grid-cols-12 gap-3 items-end">
                                        {/* Recipe Selection - Takes up most space */}
                                        <div className="col-span-12 md:col-span-7">
                                          <label className="block text-xs font-medium text-neutral-700 mb-1">
                                            Recipe
                                          </label>
                                          <RecipeSearchSelect
                                            value={entry.recipe_id}
                                            onChange={(recipeId) => updateMealEntry(entry.originalIndex, 'recipe_id', recipeId)}
                                            placeholder="Search for recipe..."
                                            initialDisplayName={getRecipeName(entry.recipe_id)}
                                          />
                                        </div>

                                        {/* Servings */}
                                        <div className="col-span-8 md:col-span-3">
                                          <Input
                                            label="Servings"
                                            type="number"
                                            value={entry.servings}
                                            onChange={(e) => updateMealEntryNumeric(entry.originalIndex, 'servings', e.target.value)}
                                            min={1}
                                            max={20}
                                            fullWidth
                                          />
                                        </div>

                                        {/* Delete Button */}
                                        <div className="col-span-4 md:col-span-2">
                                          <Button
                                            type="button"
                                            variant="outline"
                                            size="sm"
                                            onClick={() => removeMealEntry(entry.originalIndex)}
                                            className="text-error-600 hover:text-error-700 w-full h-[42px] px-2"
                                          >
                                            <Trash2 className="h-3 w-3" />
                                          </Button>
                                        </div>
                                      </div>
                                    </div>
                                  ))}
                                </div>
                              )}
                            </div>
                          ))}
                        </CardContent>
                      </Card>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}

          {/* Form Actions */}
          <div className="flex justify-end space-x-3 pt-6 border-t border-neutral-200">
            <Button type="button" variant="outline" onClick={handleClose}>
              {generatedMealPlan ? 'Close' : 'Cancel'}
            </Button>
            <Button
              type="submit"
              isLoading={isLoading}
              disabled={
                isAutoGenerate && !isEditing
                  ? !autoGenerateData.start_date || autoGenerateData.days < 1
                  : !formData.start_date || !formData.end_date
              }
            >
              {isEditing
                ? 'Update Meal Plan'
                : generatedMealPlan
                  ? 'Save Meal Plan'
                  : isAutoGenerate
                    ? 'Generate Meal Plan'
                    : 'Create Meal Plan'
              }
            </Button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default CreateMealPlanModal;
